"use client";

import { useState } from "react";
import { Download, Save, RefreshCw, FileText } from "lucide-react";
import { AnalysisData } from "@/lib/types";

interface ClinicalNotesProps {
    data: AnalysisData;
}

export default function ClinicalNotes({ data }: ClinicalNotesProps) {
    const [notes, setNotes] = useState("");

    const downloadReport = () => {
        const reportContent = `
TB CHEST X-RAY ANALYSIS REPORT
============================================================

PATIENT INFORMATION:
-------------------
Analysis Date: ${data.metadata.timestamp}
Image File: ${data.metadata.filename}

DIAGNOSTIC RESULTS:
------------------
Classification: ${data.results.prediction}
Confidence Score: ${data.results.confidence}%
Risk Level: ${data.results.risk_level}

STATISTICAL ANALYSIS:
--------------------
Original X-ray Statistics:
  - Mean: ${data.statistics.original.Mean.toFixed(2)}
  - Std Dev: ${data.statistics.original["Std Dev"].toFixed(2)}
  - Min: ${data.statistics.original.Min.toFixed(2)}
  - Max: ${data.statistics.original.Max.toFixed(2)}
  - Median: ${data.statistics.original.Median.toFixed(2)}

CLINICAL NOTES:
--------------
${notes || "No clinical notes provided."}

DISCLAIMER:
----------
This analysis is generated by an AI model for educational and 
research purposes only. Always consult with qualified medical 
professionals for diagnosis and treatment decisions.

============================================================
Report generated by TB X-ray Analyzer (Next.js Version)
    `;

        const element = document.createElement("a");
        const file = new Blob([reportContent], { type: "text/plain" });
        element.href = URL.createObjectURL(file);
        element.download = `TB_Analysis_Report_${data.metadata.filename.split('.')[0]}.txt`;
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    };

    return (
        <div className="space-y-6">
            <div className="space-y-3">
                <h3 className="text-2xl font-bold flex items-center gap-2">
                    <FileText className="w-6 h-6 text-[#ff7e5f]" /> 📝 Clinical Notes
                </h3>
                <textarea
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    placeholder="Enter any relevant clinical observations, patient history, or additional notes here..."
                    className="w-full h-32 bg-gray-800/50 border border-gray-700 rounded-xl p-4 text-gray-200 focus:outline-none focus:border-[#ff7e5f] transition-colors resize-none"
                />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <button
                    onClick={downloadReport}
                    className="flex items-center justify-center gap-2 bg-gradient-to-r from-[#ff7e5f] to-[#feb47b] hover:from-[#feb47b] hover:to-[#ff7e5f] text-white font-bold py-3 px-6 rounded-xl transition-all duration-300 shadow-lg hover:scale-105 active:scale-95"
                >
                    <Download className="w-5 h-5" /> Generate Report
                </button>
                <button
                    onClick={() => alert("Analysis saved to session (Simulated)")}
                    className="flex items-center justify-center gap-2 bg-gray-700 hover:bg-gray-600 text-white font-bold py-3 px-6 rounded-xl transition-all duration-300 shadow-lg hover:scale-105 active:scale-95"
                >
                    <Save className="w-5 h-5" /> Save Analysis
                </button>
                <button
                    onClick={() => window.location.reload()}
                    className="flex items-center justify-center gap-2 bg-gray-700 hover:bg-gray-600 text-white font-bold py-3 px-6 rounded-xl transition-all duration-300 shadow-lg hover:scale-105 active:scale-95"
                >
                    <RefreshCw className="w-5 h-5" /> Reset Analysis
                </button>
            </div>
        </div>
    );
}
